### ISSUE TITLE
f2py fails to link properly with Python 2. 

### ISSUE THREAD

**Issue by mikejwaters** [munrojm/DiSPy#1]
**Describe the bug**
f2py fails to link properly with Python 2. 
```
> dispy
Traceback (most recent call last):
  File "/home/mjwaters/software/DiSPy/bin/dispy", line 5, in <module>
    from DiSPy import init, path, dg_elements,     \
  File "/home/mjwaters/software/DiSPy/DiSPy/irr_mat.py", line 2, in <module>
    import DiSPy.irreps as irr
ImportError: No module named irreps

```
**To Reproduce**
All I did was run:
```
python setup.py install --user 
```
and then tried the examples. 
However, 
```
python3 setup.py install --user 
```
yields a fully functional install.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Additional context**
spglib was also installed with a matching version of python2 and 3 for my tests.

**Comment by munrojm** [comment]
Hi Mike, thanks for the feedback. Would you be able to provide me with the output from running `python setup.py install --user` ? I would like to see exactly where f2py is failing when it tries to compile the fortran code. You should remove the "pir_data_module.mod" file and the "build" directory from your DiSPy home directory before running the command again.

**Comment by mikejwaters** [comment]
Hi Jason, nice to talk to you again!
I removed ```pir_data_module.mod``` and reran ```python setup.py install --user```. This is my output:

```
> rm pir_data_module.mod 
> python setup.py install --user
running install
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "DiSPy.irreps" sources
f2py options: []
  adding 'build/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/DiSPy/fortranobject.c' to sources.
  adding 'build/src.linux-x86_64-2.7/build/src.linux-x86_64-2.7/DiSPy' to include_dirs.
build_src: building npy-pkg config files
running build_py
copying DiSPy/irr_mat.py -> build/lib.linux-x86_64-2.7/DiSPy
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
customize Gnu95FCompiler
Found executable /usr/bin/gfortran
customize Gnu95FCompiler
customize Gnu95FCompiler using build_ext
running build_scripts
copying and adjusting bin/dispy -> build/scripts.linux-x86_64-2.7
running install_lib
copying build/lib.linux-x86_64-2.7/DiSPy/irr_mat.py -> /home/mjwaters/.local/lib/python2.7/site-packages/DiSPy
byte-compiling /home/mjwaters/.local/lib/python2.7/site-packages/DiSPy/irr_mat.py to irr_mat.pyc
running install_scripts
copying build/scripts.linux-x86_64-2.7/dispy -> /home/mjwaters/.local/bin
changing mode of /home/mjwaters/.local/bin/dispy to 755
running install_egg_info
Removing /home/mjwaters/.local/lib/python2.7/site-packages/DiSPy-0.1.1.egg-info
Writing /home/mjwaters/.local/lib/python2.7/site-packages/DiSPy-0.1.1.egg-info
running install_clib
customize UnixCCompiler
> ls
bin  build  CHANGES.txt  DiSPy  docs  examples  LICENSE.txt  MANIFEST.in  README  README.rst  setup.py
```

Everything is working now, but I don't have ```pir_data_module.mod``` file anymore.

I also added a python version statement to my DisPy executable to help with debugging:
```
#!/usr/bin/env python

import sys
print(sys.version)

import argparse
import numpy as np

from DiSPy import init, path, dg_elements,     \
                  dg_elements_std,     \
                  irr_mat, perturb, vec_util, \
                  op_id_utils, output, dist_name
...
```

**Comment by munrojm** [comment]
Woops! My mistake. The '.mod' file doesn't need to be present in the home directory to have it run once everything is compiled. Rerunning must have solely fixed the linking issue, as it looks like f2py did not recompile anything. You can force it to recompile and relink by removing the files in "build" in the DiSPy source directory and then running the same install command. 

I have not run into any linking issues with f2py before in Python2, but will do some more testing to see if I can recreate it. Thanks again for bringing this up.

**Comment by mikejwaters** [comment]
Oh of course! It's part of being a member of the open source science community!
